# Generated by Django 3.1.2 on 2023-04-26 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230426_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.BigIntegerField(default=16777215, verbose_name='код (десятичный)'),
        ),
    ]
