# Generated by Django 3.1.2 on 2023-04-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20230426_1303'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ProductColor',
        ),
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.BigIntegerField(default=4278190080, verbose_name='код (десятичный)'),
        ),
    ]
