# Generated by Django 3.1.2 on 2023-04-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20230426_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(through='main.ProductColor', to='main.Color'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='image',
            field=models.ImageField(upload_to='main/static/main/images', verbose_name='Изображение'),
        ),
    ]
