# Generated by Django 4.2.1 on 2023-06-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_size_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='image',
            field=models.ImageField(null=True, upload_to='contacts_and_media', verbose_name='Изображение'),
        ),
    ]
